name: goreleaser

on:
  push:
    tags:
      - '*'
    branches:
      - main

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5.2.0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
